#!/bin/sh

set -e

if [ $# -ne 2 ]; then
    echo "Usage: ${0} <MESSAGE-ID> <MBOX>"
    echo 'Fetch <MESSAGE-ID> and append it to <MBOX>.'
    exit 1
fi

msgid="$1"
mbox="$2"
mbox_dir="$(dirname "$mbox")"

b4 mbox --outdir "$mbox_dir" "$msgid"
rm -f "${mbox}"
cat "$mbox_dir"/*.mbx > "${mbox}"
